defaults:
    - _self_
    - setup: default

model:
  _target_: walkjump.cmdline.utils.instantiate_model_for_sample_mode
  model_type: denoise
  checkpoint_path: ???
  denoise_path: null

langevin:
  sigma: 1.0
  delta: 0.5
  lipschitz: 1.0
  friction: 1.0
  steps: 20
  chunksize: 8

designs:
  output_csv: '/n/netscratch/mahadevan_lab/Everyone/pafischer/walk-jump-fork/running_samples.csv'
  # TOTRACK
  #redesign_regions: null
  redesign_regions: '/n/netscratch/mahadevan_lab/Everyone/pafischer/walk-jump-fork/running_csv.csv'
  seeds: denovo
  num_samples: 100
  # TOTRACK
  #limit_seeds: 10
  limit_seeds: false

device: null
